### ISSUE TITLE
Ansible host pattern

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#144]
Ansible prints "WARNING: Could not match supplied host pattern, ignoring" at the start of a run. We should triage this.

**Comment by kylelaker** [comment]
Looks like we may just need to live with it: ansible/ansible#35255

**Comment by kylelaker** [comment]
Again, this seems like it's not actually an issue has to do with host group pattern matching. This is due to our particular use case for Ansible and no combination of things in `ansible.cfg` has hidden the warning. We've only seen one or two cases where users were actually concerned about this, so I am not particularly inclined to put a lot of effort into troubleshooting much more.

**Comment by kylelaker** [comment]
This also seems to have been fixed in Ansible 2.6.0
