### ISSUE TITLE
Permission race in OEM

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#145]
Get this error when running OEM script:
``
==> Running ansible OEM playbook
[WARNING]: log file at /opt/vmtools/logs/last_run.log is not writeable and we cannot create it, aborting
``

**Comment by kylelaker** [comment]
Yeah we've always gotten that and we should decide whether it's actually a problem or not. Do we want to store logs from an OEM run in a location where they won't be deleted when the image is prepared for shipping? This happens because when the oem script is run /opt/vmtools probably doesn't exist and if it does, the oem user can't write to anything in that directory. Allowing this file to be created but not deleting it before shipping the image seems less-than-ideal, but I'm not sure I love a warning being displayed when running the role either.

**Comment by kylelaker** [comment]
I'm tempted at this point to say it's not really an issue. OEM is a behind-the-scenes thing and I'd prefer it stay out of the logs, especially since it seems like it's now appended to rather than overwritten with subsequent playbook runs.

**Comment by kylelaker** [comment]
Again, I am not particularly convinced that this is an issue. I am going to close and if we see more problems stemming from this, I am okay with reopening.
