### ISSUE TITLE
Consider adding wireless labprint connection

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#16]

**Comment by ripleymj** [comment]
Solving this may borrow heavily from this: https://github.com/kylelaker/useful_scripts/blob/master/labprintconfig

But also depend on package installation for driver support.

**Comment by ripleymj** [comment]
Requires cups-client and gtk3-print-backends

**Comment by kylelaker** [comment]
This should do it for the BW printer. For the color printer, just replace "BW" with "Color". 

        lpadmin -p "JMU-LabPrintBW" -E\
            -v "lpd://labprintremote@labprint.jmu.edu/LabPrintBW"\
            -L "JMU Labs & Libraries"\
            -m "drv:///sample.drv/generic.ppd""\
            -o "Duplex=DuplexNoTumble"\
            -o "Option1=True"

CUPS should come with the generic postscript driver by default, so that should be fine. cups-client is necessary for `lpadmin` and gtk3-print-backends will be necessary have the printers available in applications like Firefox. I'm not sure of the two `-o` options are actually necessary, but they work for me without an issue and seem to get duplex printing working (which probably isn't a bad default).

Since Ansible will be running as root, permissions shouldn't be an issue but a user will need to be in a group in the SystemGroup line in `/etc/cups/cups-file.conf` to modify the CUPS config (but that is not necessary to use the printers).

I have run this several times on a machine where the printers were already added and I did not have an issue with there being duplicate printers.

**Comment by ripleymj** [comment]
gtk3-print-backends appears to be an Arch-ism, as libprintbackend is in the libgtk-3-0 Ubuntu package.

**Comment by ripleymj** [comment]
Fixed by c76a9ad6223fed1e9c3de1528d6d559da12f1dc7 and a9cb76fcb6ffa66c896e4cc5676be560f92e6289
