### ISSUE TITLE
Check for captive portal

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#313]
One student yesterday accidentally connected to the JMU-Visitors network, behind a captive portal. When the config utility was run, it displayed a "not a valid branch" message when trying to reach GitHub. If we add a check for the Mozilla/Microsoft captive portal service, or validate the certificate for GitHub, we may be able to display a more intuitive error message.

**Comment by kylelaker** [comment]
I definitely want to avoid the difficulty of x509 parsing. So the GitHub cert option is out.

detectportal.firefox.com is nice because `if body == 'success'` then you're good. Otherwise you're not. Of course, that has the concern that maybe there are privacy issue's with using Mozilla's service. If that's acceptable I'll implement using that. Otherwise, detectportal.jmunixusers.org could always be an option.

**Comment by ripleymj** [comment]
We found in troubleshooting this that Firefox immediately makes that request anyways, so I don't think adding it to our wrapper script opens any additional privacy concerns. I still do not want to run infrastructure to support this.
