### ISSUE TITLE
101 role fails due to invalid Finch hash

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#355]
```
2019-12-11 22:45:25,043 p=1011 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "msg": "The checksum for /opt/FinchPython120.zip did not match dce5cea6562cb4b2c1f2489131227d211d559198; it was 177345bd2029f8055c53f3f078e90c72ca80c260."}
```

FinchPython120.zip appears to still be the current version, but the file contents are dated 10/24/19

**Comment by kylelaker** [comment]
So it might be hard to tell how long this has been an issue. #330 is when we started actually validating the checksum of the file we downloaded. If you run `tina` you'll see you get the file with the hash `177345bd2029f8055c53f3f078e90c72ca80c260` and you just download a new file every time because on the next run the hash doesn't match the expected value. Now that we actually validate the hash on download as well (the correct behavior), we get a hard failure.

It is alarming to me that at some point, with no announcement, a file with python scripts, dlls, and all other sorts of things had its hash change. I have tried to reach out to Bird Brain Technologies and we'll see what their response is. I don't seem to have an earlier version of this file that I could use to compare either.

I don't believe there is a section of CS 101 in the spring so I don't feel a particular urgency about this. We could always ship with either 101 or the Finch role disabled.

**Comment by ripleymj** [comment]
My small concern here is that 101'ers from last semester may try to add 159 to their image, which would re-run the Finch playbook and fail. Whether we update the hash or disable it, I'd recommend we consider a backport.

**Comment by kylelaker** [comment]
I have confirmed with BirdBrain Technologies support that `177345bd2029f8055c53f3f078e90c72ca80c260` is the expected SHA1 hash. They have said they'll pass the suggested to increment version numbers or release a changelog to their engineering team for future releases.
