### ISSUE TITLE
Review CS261 requirements

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#40]
Are `ruby`, `lua5.3`, and `lsb-core` necessary for 261, or were they just added for generic UUG purposes? Are they better better served in a role for a different course?

**Comment by lam2mo** [comment]
There is no intentional use of ruby or lua in 261, so if they are not dependencies of something (check, logisim, or valgrind, maybe?) then they do not need to be included. I do intend to use Ruby in CS430 next semester. I'm honestly not sure about lsb-core; does that package actually provide anything or is it just a way of installing a bunch of common build dependencies at once?

**Comment by ripleymj** [comment]
Ruby is a system dependency, so it wouldn't really be going away, but we wouldn't call it out as a dependency of 261. Logisim and valgrind come from apt packages, so they should trigger installations of any dependencies as determined by their maintainers. lsb-core is a strange package that pulls in a lot of odds and ends, but I think build-essential might be a closer target to what we're looking for, which is already in our list.

If you're looking for the VM for 430, let's get an issue open to track the dependencies for that and create a dedicated install target.

**Comment by kylelaker** [comment]
Debian package for lsb-core: https://packages.debian.org/sid/lsb-core
Debian package for build-essential: https://packages.debian.org/sid/build-essential

`lsb-core` was not included in the latest stable release of Debian; not sure what that means for future versions of Mint. Especially since it depends on a variety of unnecessary tools, we could try to see what `build-essential` is missing and just pull those packages in.
